version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: php_nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - "./:/var/www/app"
    depends_on:
      - app
      - mongo
    networks:
      - app-network
    command: [nginx-debug, '-g', 'daemon off;']

  app:
    container_name: php_app
    build:
      context: .
      dockerfile: ./docker/php-app/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
  
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge