test: 
	echo "API Devmunity - Wellcome"

rollback-and-migrate:
	php artisan migrate:refresh

migrate-tables:
	php artisan migrate

seed-tables:
	php artisan db:seed

clean-migration:
	php artisan migrate:reset